cocoapi can be installed as a catkin package now
plusone-robotics/cocoapi pull request #1
Opened 2023-04-18 15:26 UTC by abhijitmajumdar

2023-04-18 23:04 UTC, aaronplusone requested changes
License needs to be addressed - @shaun-edwards, care to comment? Other review feedback is minor.

2023-04-18 23:04 UTC, aaronplusone commented on README.txt
> +- Assuming your sources are located in "~/catkin_ws/src", add this repository to your sources: "git clone https://github.com/abhijitmajumdar/cocoapi.git ~/catkin_ws/src/cocoapi"
I would omit this and instead say "Add to your workspace".  The path will change and those in ROS land will understand.

2023-04-18 23:04 UTC, aaronplusone commented on package.xml
> +    <license>Proprietary</license>
I think we have to leave the license as it is. In github, it looks like a BSD-2-Clause

2023-04-18 23:04 UTC, aaronplusone commented on package.xml
> +    <description>A ROS c++ package comiling the cocoAPI</description>
```suggestion
    <description>A ROS c++ package for cocoAPI</description>
```

2023-04-18 23:04 UTC, aaronplusone commented on README.txt
> +- Once you build your package, it should build cocoapi because of the dependency tree
Omit this as well.

2023-04-18 23:13 UTC, shaun-edwards commented on package.xml
> +    <license>Proprietary</license>
@aaronplusone is correct.  Let's just add it here for completeness.  The license itself is OK to use.

2023-04-19 06:48 UTC, abhijitmajumdar commented on package.xml
> +    <license>Proprietary</license>
I replaced it with `<license>BSD-2-Clause</license>`. Is that fine?

2023-04-19 15:43 UTC, aaronplusone approved these changes

2023-04-19 15:44 UTC, merged